version: "3"
services:
  api:
    build: ./backend
    ports:
      - "8090:8090"
#    depends_on:
#      - db
    container_name: backend
  client:
    build: ./front
    ports:
      - "80:80"
    container_name: front
#  db:
#    image: mongo
#    ports:
#      - "27017:27017"
#    container_name: blog-db
