version: "3"
services:
#  api:
#    build: ./services/api
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    container_name: blog-api
  client:
    build: ./front
    ports:
      - "80:80"
    container_name: front
#  db:
#    image: mongo
#    ports:
#      - "27017:27017"
#    container_name: blog-db
