name: DEV_DEPLOY
on:
  push:
    branches: [ "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy in dev
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /usr/src/app
          rm -R docker-learn
          git clone https://github.com/Coremotor/docker-learn.git
          cd docker-learn
          git checkout develop
          docker-compose up --build -d
          docker image prune -f

    - name: Happy message
      run: echo "End deploy develop app"
