name: TEST
on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          whoami
          ls -al
          cd /usr/src/app
          git clone https://github.com/Coremotor/docker-learn.git
          cd docker-learn
          docker compose up --build
